### ISSUE TITLE
Enabling send_mail  for all users

### ISSUE THREAD

**Issue by vaijuaravind** [boev/job-direct-mail-plugin#1]
this plugin does not allow a non admin(configure) user to send mail. can this behavior be altered in the configure system?

**Comment by boev** [comment]
This is not the official repo for the plugin. It was jsut used at the start for some initial commits. The official repository (in jenkinsci) is stated in the wiki page of the plugin. Here a direct link: https://github.com/jenkinsci/job-direct-mail-plugin
Please repost your issue there.
